FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir grpcio==1.75.1 grpcio-tools==1.75.1 google-auth==2.41.1 requests==2.32.5
COPY app/youtube_chatbot.py app/chat_requests.py app/bot_conversation.py /app/
COPY app/youtube_stream_list.proto /app/
RUN python -m grpc_tools.protoc -I/app --python_out=/app --grpc_python_out=/app /app/youtube_stream_list.proto
CMD ["python", "-u", "/app/youtube_chatbot.py"]
